FEATURES = [
    {
        "id": "operations",
        "name": "Operations overview",
        "status": "available",
        "source": "GET /api/bot/operations",
        "description": "Orders, deposits, withdrawals, pending withdrawals and fees.",
    },
    {
        "id": "market",
        "name": "Market snapshot",
        "status": "available",
        "source": "GET /api/bot/market/{market}/summary",
        "description": "Activity, price, OHLC and volume for one selected market.",
    },
    {
        "id": "user-investigation",
        "name": "User investigation",
        "status": "available",
        "source": "6 GET /api/bot/user/{id}/... endpoints",
        "description": "Summary, balances, trades, deposits, withdrawals and partial PnL.",
    },
    {
        "id": "pnl",
        "name": "Complete PnL",
        "status": "partial",
        "source": "GET /api/bot/user/{id}/pnl",
        "description": "Execution PnL exists; weighted-average cost ledger is not connected.",
    },
    {
        "id": "slowdown",
        "name": "Slowdown detection",
        "status": "partial",
        "source": "Operations counts only",
        "description": "Can flag pending count; cannot yet inspect oldest age, queue or workers.",
    },
    {
        "id": "treasury",
        "name": "Treasury balances",
        "status": "missing",
        "source": "Endpoint required",
        "description": "Exchange-controlled wallet balances are not exposed.",
    },
    {
        "id": "liabilities",
        "name": "Customer liabilities",
        "status": "missing",
        "source": "Endpoint required",
        "description": "Aggregate customer balances per asset are not exposed.",
    },
    {
        "id": "queues",
        "name": "Queues and workers",
        "status": "missing",
        "source": "Endpoints required",
        "description": "Backlog, oldest job age, throughput and heartbeat are unavailable.",
    },
    {
        "id": "reconciliation",
        "name": "Reconciliation",
        "status": "missing",
        "source": "Endpoint required",
        "description": "Assets-versus-liabilities comparison is unavailable.",
    },
    {
        "id": "liquidity",
        "name": "Liquidity risk",
        "status": "missing",
        "source": "Order-book endpoint required",
        "description": "Spread and depth cannot be calculated from the current market summary.",
    },
]
