FEATURES = [
    {
        "id": "auth-v02",
        "name": "Secure request signing",
        "status": "available",
        "source": "API contract v0.2",
        "description": "Key ID, canonical query/body signing and no secret on the wire.",
    },
    {
        "id": "replay",
        "name": "Replay resistance",
        "status": "available",
        "source": "Request ID + 60s window",
        "description": "Single-use request IDs, timestamp checks and per-key rate limiting.",
    },
    {
        "id": "contracts",
        "name": "Complete API contracts",
        "status": "available",
        "source": "OpenAPI 0.2 pilot",
        "description": "Stable response fields and shared structured error schemas.",
    },
    {
        "id": "operations",
        "name": "Operations overview",
        "status": "available",
        "source": "GET /api/bot/operations",
        "description": "Orders, deposits, withdrawals, pending withdrawals and fees.",
    },
    {
        "id": "evidence-ledger",
        "name": "Aggregate evidence ledger",
        "status": "available",
        "source": "SQLite + SHA-256 chain",
        "description": "Dashboard evidence is retained locally with tamper-evident linkage.",
    },
    {
        "id": "audit-verification",
        "name": "Audit integrity verification",
        "status": "available",
        "source": "GET /api/v0/audit/verify",
        "description": "Every stored record can be verified from genesis to the current head.",
    },
    {
        "id": "historical-trends",
        "name": "Historical evidence trends",
        "status": "available",
        "source": "GET /api/v0/trends",
        "description": "Bounded period deltas and market price change from retained evidence.",
    },
    {
        "id": "freshness-alerts",
        "name": "Evidence freshness alerts",
        "status": "available",
        "source": "Rule operations-evidence-stale@1.0.0",
        "description": "Configurable stale or unknown aggregate-evidence warnings.",
    },
    {
        "id": "investigation-brief",
        "name": "Withdrawal investigation brief",
        "status": "available",
        "source": "GET /api/v0/investigations/withdrawal-slowdown",
        "description": "Conclusion, evidence, confidence, limitations and next investigation.",
    },
    {
        "id": "runbook-guidance",
        "name": "Cited runbook guidance",
        "status": "available",
        "source": "Master runbook §19",
        "description": "Deterministic triage guidance cites the approved slowdown runbook.",
    },
    {
        "id": "market",
        "name": "Market snapshot",
        "status": "available",
        "source": "GET /api/bot/market/{market}/summary",
        "description": "Activity, price, OHLC and volume for one selected market.",
    },
    {
        "id": "market-range-risk",
        "name": "Market range risk",
        "status": "partial",
        "source": "Rule market-range-percent@1.0.0",
        "description": "Analyzer is ready; live calculation requires non-zero upstream OHLC evidence.",
    },
    {
        "id": "user-investigation",
        "name": "User investigation",
        "status": "available",
        "source": "6 GET /api/bot/user/{id}/... endpoints",
        "description": "Summary, balances, trades, deposits, withdrawals and partial PnL.",
    },
    {
        "id": "pnl",
        "name": "Complete PnL",
        "status": "partial",
        "source": "GET /api/bot/user/{id}/pnl",
        "description": "Execution PnL exists; weighted-average cost ledger is not connected.",
    },
    {
        "id": "slowdown",
        "name": "Slowdown detection",
        "status": "partial",
        "source": "Operations counts only",
        "description": "Deterministic count alert exists; age, queue, worker and root cause evidence remain open.",
    },
    {
        "id": "incident-evidence",
        "name": "Evidence-backed incidents",
        "status": "available",
        "source": "Rule withdrawal-pending-count@1.0.0",
        "description": "Severity, thresholds, evidence, timeline, limitations and investigation guidance.",
    },
    {
        "id": "treasury",
        "name": "Treasury balances",
        "status": "missing",
        "source": "Endpoint required",
        "description": "Exchange-controlled wallet balances are not exposed.",
    },
    {
        "id": "pagination",
        "name": "Bounded pagination",
        "status": "partial",
        "source": "Limit 1–100",
        "description": "Page limits exist; cursor pagination and next_cursor remain open.",
    },
    {
        "id": "timestamps",
        "name": "UTC timestamps",
        "status": "partial",
        "source": "Mixed ISO 8601 / MySQL UTC",
        "description": "Freshness fields are ISO 8601; legacy transaction fields need normalization.",
    },
    {
        "id": "upstream-health",
        "name": "Exchange dependency health",
        "status": "missing",
        "source": "GET /api/bot/health required",
        "description": "Local health exists; upstream API and core dependency health are not exposed.",
    },
    {
        "id": "liabilities",
        "name": "Customer liabilities",
        "status": "missing",
        "source": "Endpoint required",
        "description": "Aggregate customer balances per asset are not exposed.",
    },
    {
        "id": "queues",
        "name": "Queues and workers",
        "status": "missing",
        "source": "Endpoints required",
        "description": "Backlog, oldest job age, throughput and heartbeat are unavailable.",
    },
    {
        "id": "reconciliation",
        "name": "Reconciliation",
        "status": "missing",
        "source": "Endpoint required",
        "description": "Assets-versus-liabilities comparison is unavailable.",
    },
    {
        "id": "liquidity",
        "name": "Liquidity risk",
        "status": "partial",
        "source": "Order-book endpoint required",
        "description": "Range risk exists; spread, depth and divergence still require new endpoints.",
    },
]
