FEATURES = [
    {
        "id": "domain-agent-chats",
        "name": "Eight domain agent chats",
        "status": "available",
        "source": "/agents/{operations|market-risk|treasury|aml-fraud|security|support|executive|governance}",
        "description": "Separate domain-bound, sampled, cited, audited, read-only chat workspaces.",
    },
    {
        "id": "operations-root-cause",
        "name": "Operations topology and root-cause analysis",
        "status": "available",
        "source": "POST /api/v0/xima/agents/operations/analyze",
        "description": "Correlates services, dependencies, queue rates, dead letters, workers, capacity and networks while labeling causal candidates as hypotheses.",
    },
    {
        "id": "market-liquidity-package",
        "name": "Normalized market and liquidity package",
        "status": "available",
        "source": "POST /api/v0/xima/agents/market-risk/analyze",
        "description": "Validates books, tickers, trades and candles; measures depth bands, imbalance, gaps, divergence, exposure, concentration and governed limits.",
    },
    {
        "id": "readonly-chat",
        "name": "Read-only evidence chat",
        "status": "available",
        "source": "POST /api/v0/chat",
        "description": "Ollama answers over retained evidence with citations, refusal and audit.",
    },
    {
        "id": "auth-v02",
        "name": "Secure request signing",
        "status": "available",
        "source": "API contract v0.2",
        "description": "Key ID, canonical query/body signing and no secret on the wire.",
    },
    {
        "id": "replay",
        "name": "Replay resistance",
        "status": "available",
        "source": "Request ID + 60s window",
        "description": "Single-use request IDs, timestamp checks and per-key rate limiting.",
    },
    {
        "id": "contracts",
        "name": "Complete API contracts",
        "status": "available",
        "source": "OpenAPI 0.8.0-pilot",
        "description": "Contract envelope, scoped reads, structured errors, quality and lineage metadata.",
    },
    {
        "id": "operations",
        "name": "Operations overview",
        "status": "available",
        "source": "GET /api/bot/operations",
        "description": "Orders, deposits, withdrawals, pending withdrawals and fees.",
    },
    {
        "id": "evidence-ledger",
        "name": "Aggregate evidence ledger",
        "status": "available",
        "source": "SQLite + SHA-256 chain",
        "description": "Dashboard evidence is retained locally with tamper-evident linkage.",
    },
    {
        "id": "audit-verification",
        "name": "Audit integrity verification",
        "status": "available",
        "source": "GET /api/v0/audit/verify",
        "description": "Every stored record can be verified from genesis to the current head.",
    },
    {
        "id": "historical-trends",
        "name": "Historical evidence trends",
        "status": "available",
        "source": "GET /api/v0/trends",
        "description": "Bounded period deltas and market price change from retained evidence.",
    },
    {
        "id": "freshness-alerts",
        "name": "Evidence freshness alerts",
        "status": "available",
        "source": "Rule operations-evidence-stale@1.0.0",
        "description": "Configurable stale or unknown aggregate-evidence warnings.",
    },
    {
        "id": "investigation-brief",
        "name": "Withdrawal investigation brief",
        "status": "available",
        "source": "GET /api/v0/investigations/withdrawal-slowdown",
        "description": "Conclusion, evidence, confidence, limitations and next investigation.",
    },
    {
        "id": "runbook-guidance",
        "name": "Cited runbook guidance",
        "status": "available",
        "source": "Master runbook §19",
        "description": "Deterministic triage guidance cites the approved slowdown runbook.",
    },
    {
        "id": "executive-brief",
        "name": "Daily executive brief",
        "status": "available",
        "source": "GET /api/v0/briefs/daily",
        "description": "Deterministic priorities, evidence, confidence and limitations.",
    },
    {
        "id": "operator-feedback",
        "name": "Operator feedback",
        "status": "available",
        "source": "POST /api/v0/feedback (local only)",
        "description": "Append-only ratings and corrections that never write upstream.",
    },
    {
        "id": "rbac-policy",
        "name": "Role capability policy",
        "status": "partial",
        "source": "X-BitAgent-Role pilot header",
        "description": "Observe/enforced RBAC exists; production SSO/JWT identity proof is still required.",
    },
    {
        "id": "refusal-policy",
        "name": "Prohibited-action refusal",
        "status": "available",
        "source": "POST /api/v0/policy/evaluate",
        "description": "Fund, trade, balance, user and configuration actions are always denied.",
    },
    {
        "id": "access-audit",
        "name": "Access decision audit",
        "status": "available",
        "source": "GET /api/v0/audit/access/recent",
        "description": "Allowed, denied and observe-mode decisions are retained with hashes.",
    },
    {
        "id": "historical-replay",
        "name": "Sanitized incident replay",
        "status": "available",
        "source": "GET /api/v0/evaluations/replay",
        "description": "Six golden cases validate deterministic severity boundaries.",
    },
    {
        "id": "uat-readiness",
        "name": "Pilot readiness gates",
        "status": "partial",
        "source": "GET /api/v0/readiness",
        "description": "Machine-readable pass, fail and pending gates prevent false go-live claims.",
    },
    {
        "id": "market",
        "name": "Market snapshot",
        "status": "available",
        "source": "GET /api/bot/market/{market}/summary",
        "description": "Activity, price, OHLC and volume for one selected market.",
    },
    {
        "id": "market-range-risk",
        "name": "Market range risk",
        "status": "partial",
        "source": "Rule market-range-percent@1.0.0",
        "description": "Analyzer is ready; live calculation requires non-zero upstream OHLC evidence.",
    },
    {
        "id": "user-investigation",
        "name": "User investigation",
        "status": "available",
        "source": "6 GET /api/bot/user/{id}/... endpoints",
        "description": "Summary, balances, trades, deposits, withdrawals and partial PnL.",
    },
    {
        "id": "pnl",
        "name": "Complete PnL",
        "status": "partial",
        "source": "GET /api/bot/user/{id}/pnl",
        "description": "Execution PnL exists; weighted-average cost ledger is not connected.",
    },
    {
        "id": "slowdown",
        "name": "Slowdown detection",
        "status": "partial",
        "source": "Operations counts only",
        "description": "Deterministic count alert exists; age, queue, worker and root cause evidence remain open.",
    },
    {
        "id": "incident-evidence",
        "name": "Evidence-backed incidents",
        "status": "available",
        "source": "Rule withdrawal-pending-count@1.0.0",
        "description": "Severity, thresholds, evidence, timeline, limitations and investigation guidance.",
    },
    {
        "id": "treasury",
        "name": "Treasury balances",
        "status": "available",
        "source": "GET /api/bot/treasury/assets",
        "description": "Crypto custody totals and deduplicated company IRT balances with partial-source warnings.",
    },
    {
        "id": "pagination",
        "name": "Bounded pagination",
        "status": "partial",
        "source": "Pending cursor + user limit 1–100",
        "description": "Pending transaction routes use keyset cursors; legacy user activity remains limit-only.",
    },
    {
        "id": "timestamps",
        "name": "UTC timestamps",
        "status": "partial",
        "source": "Mixed ISO 8601 / MySQL UTC",
        "description": "Freshness fields are ISO 8601; legacy transaction fields need normalization.",
    },
    {
        "id": "upstream-health",
        "name": "Exchange dependency health",
        "status": "available",
        "source": "GET /api/bot/health",
        "description": "Backend, database, matching-engine, maintenance, clock, and dependency state are exposed.",
    },
    {
        "id": "liabilities",
        "name": "Customer liabilities",
        "status": "available",
        "source": "GET /api/bot/ledger/liabilities",
        "description": "Snapshot-based aggregate available, locked, total, and negative-balance evidence by asset.",
    },
    {
        "id": "queues",
        "name": "Queues and workers",
        "status": "missing",
        "source": "Endpoints required",
        "description": "Backlog, oldest job age, throughput and heartbeat are unavailable.",
    },
    {
        "id": "reconciliation",
        "name": "Reconciliation",
        "status": "partial",
        "source": "GET /api/v0/exchange/treasury-intelligence",
        "description": "Operational assets-versus-liabilities comparison exists; stale/manual sources prevent proof-of-reserves claims.",
    },
    {
        "id": "liquidity",
        "name": "Liquidity risk",
        "status": "partial",
        "source": "Order-book endpoint required",
        "description": "Range risk exists; spread, depth and divergence still require new endpoints.",
    },
    {
        "id": "xima-evidence-platform",
        "name": "XIMA normalized evidence platform",
        "status": "available",
        "source": "POST /api/v0/xima/evidence",
        "description": "Tenant-scoped schemas, lineage, freshness, quality, replay and hash-chain audit.",
    },
    {
        "id": "xima-domain-agents",
        "name": "XIMA domain intelligence agents",
        "status": "available",
        "source": "/api/v0/xima/agents/*",
        "description": "Operations, market/risk, treasury, AML/fraud, security and support analysis contracts.",
    },
    {
        "id": "xima-governed-knowledge",
        "name": "XIMA governed knowledge",
        "status": "available",
        "source": "/api/v0/xima/knowledge/*",
        "description": "Multi-format extraction, chunk hashes, duplicate controls, inventory, append-only lifecycle events, cited retrieval and evaluation.",
    },
    {
        "id": "xima-governance-evaluation",
        "name": "XIMA governance and evaluation",
        "status": "available",
        "source": "/api/v0/xima/governance/*",
        "description": "Cross-domain policy, registry, quality, safety, cost, latency and drift gates.",
    },
    {
        "id": "xima-shadow-readiness",
        "name": "XIMA shadow-pilot readiness",
        "status": "available",
        "source": "POST /api/v0/xima/pilot/shadow/evaluate",
        "description": "Outcome, noise, reliability, training and owner-evidence gates remain fail-closed.",
    },
    {
        "id": "xima-action-sandbox",
        "name": "XIMA low-risk action sandbox",
        "status": "available",
        "source": "/api/v0/xima/actions/*",
        "description": "Exact signed maker-checker authorization, idempotency, verification, rollback and kill switch.",
    },
    {
        "id": "xima-executive-intelligence",
        "name": "XIMA cross-domain executive intelligence",
        "status": "available",
        "source": "POST /api/v0/xima/agents/executive/brief",
        "description": "Complete fresh-domain coverage, priorities, KPIs, evidence, owners and next actions.",
    },
    {
        "id": "xima-resilient-gateway",
        "name": "XIMA resilient read-only gateway",
        "status": "available",
        "source": "GET /api/v0/xima/integrations/exchange/health",
        "description": "Bounded retry/backoff, circuit breaking and credential-free source telemetry.",
    },
]
